// AUTO-GÉNÉRÉ depuis le scraping de ines-garden.com (fiches produits réelles).
// 76 produits · 8 collections · prix, dimensions, poids, descriptif et images d'origine.

import type { Product, CategoryMeta } from "./catalog";

export const CATEGORIES: CategoryMeta[] = [
  {
    slug: "vases-medicis",
    name: "Vases Médicis", nameEn: "Medici Vases",
    tagline: "La pièce signature", taglineEn: "The signature piece",
    description: "Le grand classique des jardins à la française, reproduit en fonte de fer du modèle de table au géant monumental. Galbe profond, anses en volute, patine qui se bonifie dehors.", descriptionEn: "The great classic of French formal gardens, cast in iron from tabletop model to monumental giant.",
    hero: "/clients/ines-garden/products/vases-medicis/46-vase-medicis-en-fonte-bronze-vert-1.jpg",
    gallery: [
      "/clients/ines-garden/products/vases-medicis/46-vase-medicis-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/vases-medicis/58-vase-medicis-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/vases-medicis/8-vase-medicis-en-fonte-patine-bronze-vert-1.jpg",
      "/clients/ines-garden/products/vases-medicis/40-vase-medicis-en-fonte-bronze-vert-1.jpg",
    ],
    count: 35, priceFrom: 60, priceTo: 14900,
  },
  {
    slug: "vasques-medicis",
    name: "Vasques Médicis", nameEn: "Medici Basins",
    tagline: "Le bassin ornemental", taglineEn: "The ornamental basin",
    description: "Larges vasques évasées à poser au sol ou sur colonne, pour un point d'eau ou une composition florale. De la vasque d'entrée à la pièce de bassin monumentale.", descriptionEn: "Wide flared basins for a water feature or floral display, from entrance piece to monumental pond centrepiece.",
    hero: "/clients/ines-garden/products/vasques-medicis/78-vasque-medicis-en-fonte-bronze-marron-1.jpg",
    gallery: [
      "/clients/ines-garden/products/vasques-medicis/78-vasque-medicis-en-fonte-bronze-marron-1.jpg",
      "/clients/ines-garden/products/vasques-medicis/62-vasque-medicis-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/vasques-medicis/68-vasque-fontaine-oiseaux-bronze-vert-1.jpg",
    ],
    count: 11, priceFrom: 175, priceTo: 14800,
  },
  {
    slug: "fontaines",
    name: "Fontaines", nameEn: "Fountains",
    tagline: "Le point d'eau", taglineEn: "The water feature",
    description: "Fontaines en fonte à un, deux ou trois étages, jusqu'à 3,60 m. Le geste central qui structure tout un jardin autour du bruit de l'eau.", descriptionEn: "One-, two- or three-tier cast-iron fountains up to 3.6 m — the centrepiece that anchors a whole garden.",
    hero: "/clients/ines-garden/products/fontaines/105-fontaine-en-fonte-bronze-vert-1.jpg",
    gallery: [
      "/clients/ines-garden/products/fontaines/105-fontaine-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/fontaines/103-fontaine-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/fontaines/121-fontaine-en-fonte-3-etages-bronze-vert-1.jpeg",
    ],
    count: 3, priceFrom: 1100, priceTo: 11690,
  },
  {
    slug: "statues",
    name: "Statues 4 saisons", nameEn: "Four Seasons Statues",
    tagline: "Les allégories", taglineEn: "The allegories",
    description: "Statues en fonte des quatre saisons, de 150 à 233 cm, sur socle ou base assortie. Finitions blanc, pierre ou bronze bleuté pour ponctuer une allée.", descriptionEn: "Cast-iron Four Seasons statues, 150 to 233 cm, on plinth or matching base.",
    hero: "/clients/ines-garden/products/statues/111-statue-en-fonte-4-saisons-pierre-1.jpg",
    gallery: [
      "/clients/ines-garden/products/statues/111-statue-en-fonte-4-saisons-pierre-1.jpg",
      "/clients/ines-garden/products/statues/110-statue-en-fonte-4-saisons-pierre-1.jpg",
      "/clients/ines-garden/products/statues/106-statue-en-fonte-4-saisons-blanc-1.jpg",
      "/clients/ines-garden/products/statues/108-statue-en-fonte-4-saisons-blanc-1.jpg",
    ],
    count: 12, priceFrom: 3500, priceTo: 6510,
  },
  {
    slug: "bacs-a-oranger",
    name: "Bacs à oranger", nameEn: "Orangery Boxes",
    tagline: "L'esprit Versailles", taglineEn: "The Versailles spirit",
    description: "Caisses en fonte façon caisses de Versailles, décorées de croix et de cercles. Pour agrumes, lauriers et topiaires en pleine lumière.", descriptionEn: "Versailles-style cast-iron crates for citrus, bay and topiary.",
    hero: "/clients/ines-garden/products/bacs-a-oranger/81-bac-a-oranger-en-fonte-bronze-vert-1.jpg",
    gallery: [
      "/clients/ines-garden/products/bacs-a-oranger/81-bac-a-oranger-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/bacs-a-oranger/83-bac-a-oranger-bronze-vert-1.jpg",
    ],
    count: 2, priceFrom: 510, priceTo: 2500,
  },
  {
    slug: "jardinieres",
    name: "Jardinières", nameEn: "Planters",
    tagline: "Le petit ornement", taglineEn: "The small ornament",
    description: "Jardinières en fonte à poser sur un rebord, un muret ou une table de jardin. Le détail patiné qui habille sans encombrer.", descriptionEn: "Cast-iron planters for a sill, low wall or garden table — the patinated detail.",
    hero: "/clients/ines-garden/products/jardinieres/99-jardiniere-en-fonte-bronze-vert-1.jpg",
    gallery: [
      "/clients/ines-garden/products/jardinieres/99-jardiniere-en-fonte-bronze-vert-1.jpg",
      "/clients/ines-garden/products/jardinieres/88-jardiniere-en-fonte-gris-1.jpg",
      "/clients/ines-garden/products/jardinieres/84-jardiniere-en-fonte-bronze-marron-1.jpg",
    ],
    count: 11, priceFrom: 50, priceTo: 360,
  },
  {
    slug: "tetes-de-cheval",
    name: "Têtes de cheval", nameEn: "Horse Heads",
    tagline: "La création maison", taglineEn: "The house creation",
    description: "Tête de cheval en fonte, création exclusive des Jardins d'Inès. Sculpture équestre pour un portail, un mur ou un pilier.", descriptionEn: "A cast-iron horse head, exclusive to Les Jardins d'Inès — an equestrian sculpture for a gate or pillar.",
    hero: "/clients/ines-garden/products/tetes-de-cheval/102-tete-de-cheval-en-fonte-bronze-vert-1.jpg",
    gallery: [
      "/clients/ines-garden/products/tetes-de-cheval/102-tete-de-cheval-en-fonte-bronze-vert-1.jpg",
    ],
    count: 1, priceFrom: 570, priceTo: 570,
  },
  {
    slug: "salons-de-jardin",
    name: "Salons de jardin", nameEn: "Garden Sets",
    tagline: "L'assise en fonte", taglineEn: "Cast-iron seating",
    description: "Salon de jardin en fonte, table et chaises de style ancien. Robuste, résistant aux intempéries, fait pour rester dehors toute l'année.", descriptionEn: "A cast-iron garden set, antique-style table and chairs, built to stay outdoors year round.",
    hero: "/clients/ines-garden/products/salons-de-jardin/80-salon-de-jardin-en-fonte-noir-1.jpg",
    gallery: [
      "/clients/ines-garden/products/salons-de-jardin/80-salon-de-jardin-en-fonte-noir-1.jpg",
    ],
    count: 1, priceFrom: 1900, priceTo: 1900,
  },
];

export const PRODUCTS: Product[] = [
  {
    slug: "15-vase-medicis-en-fonte-bronze-vert", id: "15", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 24 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP3A bv",
    price: 60, height: "24 cm", width: "18 cm",
    footBase: "9,5 cm", weight: "3,5 kg", stock: 17,
    description: "Très joli vase Médicis classique en fonte, idéal comme idée cadeau. Cet ensemble peut trouver aisément sa place dans votre jardin ou à l'intérieur et sera extrêmement élégant et décoratif.",
    img: "/clients/ines-garden/products/vases-medicis/15-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "18-vase-medicis-en-fonte-bronze-vert", id: "18", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 32 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP3B bv",
    price: 90, height: "32 cm", width: "23,5 cm",
    footBase: "12,5 cm", weight: "6 kg", stock: 10,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Ce vase est équipé d'une evacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/18-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "22-vase-medicis-en-fonte-gris", id: "22", category: "vases-medicis",
    name: "Vase Médicis · Gris 37 cm", baseName: "Vase Médicis en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP245A g",
    price: 115, height: "37 cm", width: "28 cm",
    footBase: "6,5 cm", weight: "8 kg", stock: 1,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Grâce à sa base, il se pose directement sur de la pelouse ou dans des graviers, au bord d'une piscine, en bas d'un escalier...",
    img: "/clients/ines-garden/products/vases-medicis/22-vase-medicis-en-fonte-gris-1.jpg",
  },
  {
    slug: "23-chandelier-en-fonte-bronze-marron", id: "23", category: "vases-medicis",
    name: "Vase Médicis · Bronze-marron 70,5 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-marron", swatch: "#6b4c34", ref: "chandelier",
    price: 140, height: "70,5 cm", width: "24 cm",
    footBase: "24 cm", weight: undefined, stock: 1,
    description: "Très beau Chandelier en fonte qui peut trouver sa place à coté d'une cheminée posé directement au sol. Peut accueillir des bougies très larges de 8 cm environ.",
    img: "/clients/ines-garden/products/vases-medicis/23-chandelier-en-fonte-bronze-marron-1.jpg",
  },
  {
    slug: "126-panneau-en-fonte-bronze-marron", id: "126", category: "vases-medicis",
    name: "Vase Médicis · Bronze-marron 123 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-marron", swatch: "#6b4c34", ref: "Panneau",
    price: 150, height: "123 cm", width: "65 cm",
    footBase: "20 cm", weight: "45 kg", stock: 1,
    description: "Joli panneau en fonte d'occasion sur pied sur lequel vous pouvez écrire pour donner une information. Ce Panneau est actuellement couleur bronze marron mais peut aussi bien se repeindre de la couleur que vous souhaitez Ligne. Ils sont en promotion car ce sont les derniers que nous avons dans notre stock.",
    img: "/clients/ines-garden/products/vases-medicis/126-panneau-en-fonte-bronze-marron-1.jpeg",
  },
  {
    slug: "133-vase-medicis-en-fonte-bronze-vert", id: "133", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 43 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP1B bv",
    price: 180, height: "43 cm", width: "32 cm",
    footBase: "16 cm", weight: "12 kg", stock: 29,
    description: "Ce ravissant vase Médicis en fonte apportera une touche de charme intemporel à votre jardin comme à votre intérieur. Conçu pour être mis en valeur sur un socle, un pilier d’entrée ou un meuble, ce modèle de petite taille n’est pas destiné à être posé directement au sol, ce qui renforce son allure raffinée. Comme tous nos vases Médicis, il est doté d’un système d’évacuation de l’eau, vous permettant d’y installer de véritables plantes en toute simplicité. Une pièce décorative de caractère, aussi esthétique que fonctionnelle.",
    img: "/clients/ines-garden/products/vases-medicis/133-vase-medicis-en-fonte-bronze-vert-1.jpeg",
  },
  {
    slug: "26-vase-medicis-en-fonte-gris", id: "26", category: "vases-medicis",
    name: "Vase Médicis · Gris 43 cm", baseName: "Vase Médicis en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP1B g",
    price: 180, height: "43 cm", width: "32 cm",
    footBase: "16 cm", weight: "12 kg", stock: 1,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Grâce à sa base, il se pose directement sur de la pelouse ou dans des graviers, au bord d'une piscine, en bas d'un escalier...",
    img: "/clients/ines-garden/products/vases-medicis/26-vase-medicis-en-fonte-gris-1.jpg",
  },
  {
    slug: "127-fontaine-style-western-bronze-marron", id: "127", category: "vases-medicis",
    name: "Vase Médicis · Bronze-marron 130 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-marron", swatch: "#6b4c34", ref: "Fontaine WTR",
    price: 290, height: "130 cm", width: "17 cm",
    footBase: "25 cm", weight: "37 kg", stock: 1,
    description: "Très belle fontaine à poussoir, couleur patine, bronze, marron, un élément très décoratif pour votre jardin. C'est le dernier qui nous reste en stock c'est pour cela qu'il est en promotion actuellement. Possibilité de le repeindre de la couleur que vous souhaitez",
    img: "/clients/ines-garden/products/vases-medicis/127-fontaine-style-western-bronze-marron-1.jpeg",
  },
  {
    slug: "120-socle-en-fonte-noir", id: "120", category: "vases-medicis",
    name: "Vase Médicis · Noir 63 cm", baseName: "Vase Médicis en fonte",
    color: "Noir", swatch: "#242220", ref: "Base 76",
    price: 390, height: "63 cm", width: "44 cm",
    footBase: undefined, weight: "70 kg", stock: 10,
    description: "Ce magnifique socle en fonte qui pourra vous servir de support pour votre vases medicis ou tout autre objet décoratif aussi bien à l'extérieur qu'à l'intérieur de votre maison. Ce socle est creux à l'intérieur ce qui permet d'évacuation de l'eau si vous avez une plante dans votre bien décoratif.",
    img: "/clients/ines-garden/products/vases-medicis/120-socle-en-fonte-noir-1.jpeg",
  },
  {
    slug: "40-vase-medicis-en-fonte-bronze-vert", id: "40", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 60 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP351 bv",
    price: 440, height: "60 cm", width: "44 cm",
    footBase: "28,5 cm", weight: "32 kg", stock: 7,
    description: "Très joli vase Médicis classique avec une coupe droite en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi décorer une entrée ou se mettre à l'intérieur de votre maison. Possibilité de planter grâce à un évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/40-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "43-vase-en-fonte-noir-mat", id: "43", category: "vases-medicis",
    name: "Vase Médicis · Noir mat 74 cm", baseName: "Vase Médicis en fonte",
    color: "Noir mat", swatch: "#1e1c1a", ref: "HSP326",
    price: 470, height: "74 cm", width: "51 cm",
    footBase: undefined, weight: "57 kg", stock: 2,
    description: "Très beau vase en fonte moderne.",
    img: "/clients/ines-garden/products/vases-medicis/43-vase-en-fonte-noir-mat-1.jpg",
  },
  {
    slug: "44-vase-en-fonte-noir-mat", id: "44", category: "vases-medicis",
    name: "Vase Médicis · Noir mat 80 cm", baseName: "Vase Médicis en fonte",
    color: "Noir mat", swatch: "#1e1c1a", ref: "HSM103A n",
    price: 490, height: "80 cm", width: "40 cm",
    footBase: undefined, weight: "66 kg", stock: 2,
    description: "Très beau vase en fonte moderne.",
    img: "/clients/ines-garden/products/vases-medicis/44-vase-en-fonte-noir-mat-1.jpg",
  },
  {
    slug: "42-vase-medicis-en-fonte-bronze-vert", id: "42", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 61 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP245B bv",
    price: 490, height: "61 cm", width: "44 cm",
    footBase: "26,5 cm", weight: "33 kg", stock: 30,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi décorer une entrée ou se mettre à l'intérieur de votre maison. Possibilité de planter grâce à un évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/42-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "46-vase-medicis-en-fonte-bronze-vert", id: "46", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 70 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP9B bv",
    price: 550, height: "70 cm", width: "47,5 cm",
    footBase: "26 cm", weight: "40 kg", stock: 11,
    description: "Très joli vase Médicis classique avec une coupe droite en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi décorer une entrée ou se mettre à l'intérieur de votre maison. Possibilité de planter grâce à une évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/46-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "49-vase-en-fonte-noir-mat", id: "49", category: "vases-medicis",
    name: "Vase Médicis · Noir mat 100 cm", baseName: "Vase Médicis en fonte",
    color: "Noir mat", swatch: "#1e1c1a", ref: "HSP325 n",
    price: 590, height: "100 cm", width: "54 cm",
    footBase: undefined, weight: "69 kg", stock: 2,
    description: "Très beau vase en fonte moderne.",
    img: "/clients/ines-garden/products/vases-medicis/49-vase-en-fonte-noir-mat-1.jpg",
  },
  {
    slug: "38-vase-medicis-en-fonte-bronze-vert", id: "38", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 77 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP13A bv",
    price: 640, height: "77 cm", width: "59 cm",
    footBase: "26,5 cm", weight: "46,5 kg", stock: 8,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi décorer une entrée ou se mettre à l'intérieur de votre maison. Possibilité de planter grâce à une évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/38-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "37-vase-medicis-en-fonte-noir", id: "37", category: "vases-medicis",
    name: "Vase Médicis · Noir 77 cm", baseName: "Vase Médicis en fonte",
    color: "Noir", swatch: "#242220", ref: "HSP13A n",
    price: 640, height: "77 cm", width: "59 cm",
    footBase: undefined, weight: "46,5 kg", stock: 8,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi décorer une entrée ou se mettre à l'interieur de votre maison. Possibilité de planter grâce à une évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/37-vase-medicis-en-fonte-noir-1.jpg",
  },
  {
    slug: "131-vase-medicis-en-fonte-cannele-bronze-vert", id: "131", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 70,5 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP37F bv",
    price: 690, height: "70,5 cm", width: "56 cm",
    footBase: "28 cm", weight: "50 kg", stock: 8,
    description: "Inspiré du célèbre Vase Médicis , chef-d’œuvre antique du Ier siècle av. J.-C. exposé à la Galerie des Offices à Florence, ce vase reprend les codes esthétiques qui ont marqué plus de deux millénaires d’art décoratif. Réapparu à la Renaissance dans les collections de la puissante famille Médicis, ce modèle est devenu un symbole de prestige et d’élégance dans les jardins princiers européens. Les cannelures verticales , héritées des colonnes grecques et romaines, apportent relief et noblesse à la silhouette du vase, en soulignant son caractère classique. Reproduit en fonte au fil des siècles pour orner parcs, demeures et entrées majestueuses, le vase Médicis demeure aujourd’hui une pièce emblématique, à la fois décorative et intemporelle.",
    img: "/clients/ines-garden/products/vases-medicis/131-vase-medicis-en-fonte-cannele-bronze-vert-1.jpeg",
  },
  {
    slug: "53-vase-medicis-en-fonte-bronze-vert", id: "53", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 76 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP245C bv",
    price: 890, height: "76 cm", width: "56 cm",
    footBase: "34 cm", weight: "60 kg", stock: 20,
    description: "Superbe vase médicis classique en fonte. Son gros volume peut lui permettre d'accueillir des plantes qui ont besoin de place.",
    img: "/clients/ines-garden/products/vases-medicis/53-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "51-vase-medicis-en-fonte-noir-mat", id: "51", category: "vases-medicis",
    name: "Vase Médicis · Noir mat 76 cm", baseName: "Vase Médicis en fonte",
    color: "Noir mat", swatch: "#1e1c1a", ref: "HSP245C n",
    price: 890, height: "76 cm", width: "56 cm",
    footBase: "34 cm", weight: "60 kg", stock: 30,
    description: "Très beau vase Médicis en fonte classique patiné bronze-vert. Equipé d'une évacuation et d'un grand volume intérieur il peut accueillir des plantes de grande tailles. Ce vase Médicis peut se mettre aussi bien à l'intérieur de votre maison que dans votre jardin, entrée, piscine ou terrasse.",
    img: "/clients/ines-garden/products/vases-medicis/51-vase-medicis-en-fonte-noir-mat-1.jpg",
  },
  {
    slug: "132-vase-medicis-en-fonte-cannele-bronze-vert", id: "132", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 80 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP288 bv",
    price: 940, height: "80 cm", width: "63 cm",
    footBase: "29 cm", weight: "70 kg", stock: 6,
    description: "Inspiré du célèbre Vase Médicis , chef-d’œuvre antique du Ier siècle av. J.-C. exposé à la Galerie des Offices à Florence, ce vase reprend les codes esthétiques qui ont marqué plus de deux millénaires d’art décoratif. Réapparu à la Renaissance dans les collections de la puissante famille Médicis, ce modèle est devenu un symbole de prestige et d’élégance dans les jardins princiers européens. Les cannelures verticales , héritées des colonnes grecques et romaines, apportent relief et noblesse à la silhouette du vase, en soulignant son caractère classique. Reproduit en fonte au fil des siècles pour orner parcs, demeures et entrées majestueuses, le vase Médicis demeure aujourd’hui une pièce emblématique, à la fois décorative et intemporelle.",
    img: "/clients/ines-garden/products/vases-medicis/none-vase-medicis-en-fonte-cannele-bronze-vert-1.jpeg",
  },
  {
    slug: "48-vase-medicis-en-fonte-noir", id: "48", category: "vases-medicis",
    name: "Vase Médicis · Noir 95 cm", baseName: "Vase Médicis en fonte",
    color: "Noir", swatch: "#242220", ref: "HSP13C n",
    price: 990, height: "95 cm", width: "65 cm",
    footBase: "34 cm", weight: "71 kg", stock: 6,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi décorer une entrée ou se mettre à l'intérieur de votre maison. Possibilité de planter grâce à une évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/48-vase-medicis-en-fonte-noir-1.jpg",
  },
  {
    slug: "47-vase-medicis-en-fonte-bronze-vert", id: "47", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 95 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP13C bv",
    price: 990, height: "95 cm", width: "65 cm",
    footBase: "34 cm", weight: "71 kg", stock: 6,
    description: "Très joli vase Médicis classique en fonte. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif. Il peut aussi decorer une entrée ou se mettre à l'interieur de votre maison. Possibilité de planter grâce à une évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/47-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "118-vase-medicis-en-fonte-bronze-vert", id: "118", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 111 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP245B+B77 bv",
    price: 1125, height: "111 cm", width: "62 cm",
    footBase: "20 cm", weight: "80 kg", stock: 4,
    description: "Magnifique Vase Médicis classique en fonte posé sur sa base pour le mettre en valeur. Cette paire de vases Médicis en fonte décore très élégamment un grand jardin ou une entrée. Son volume lui permet de recevoir de belles plantes qui ont besoin d'espace.",
    img: "/clients/ines-garden/products/vases-medicis/118-vase-medicis-en-fonte-bronze-vert-1.jpeg",
  },
  {
    slug: "128-vase-medicis-en-fonte-pierre", id: "128", category: "vases-medicis",
    name: "Vase Médicis · Pierre 86 cm", baseName: "Vase Médicis en fonte",
    color: "Pierre", swatch: "#cabfae", ref: "HSP245E p",
    price: 1190, height: "86 cm", width: "62 cm",
    footBase: "38 cm", weight: "76 kg", stock: 2,
    description: "NOUVEAU MODÈLE DISPONIBLE, ce magnifique vase medicis en fonte très bien proportionné de notre gamme actuelle (HSP245) qui viens donner une alternative supplémentaire au niveau des dimensions car il se situe entre 2 de nos best seller le HSP245C et HSP245D. Il sera parfait à poser au sol et son grand volume intérieur vous permettra un choix important de plantes pour décorer et mettre en valeur votre vase medicis en fonte.",
    img: "/clients/ines-garden/products/vases-medicis/128-vase-medicis-en-fonte-pierre-1.jpg",
  },
  {
    slug: "130-vase-medicis-en-fonte-bronze-ardoise", id: "130", category: "vases-medicis",
    name: "Vase Médicis · Bronze-ardoise 86 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-ardoise", swatch: "#4a4f57", ref: "HSP245E bb",
    price: 1190, height: "86 cm", width: "62 cm",
    footBase: "38 cm", weight: "46 kg", stock: 6,
    description: "Ce magnifique vase médicis sera parfait pour décorer votre jardin Ou bien l'entrée de votre maison",
    img: "/clients/ines-garden/products/vases-medicis/130-vase-medicis-en-fonte-bronze-ardoise-1.jpeg",
  },
  {
    slug: "4-vase-medicis-en-fonte-bronze-vert", id: "4", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 126 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP13A+B77 bv",
    price: 1250, height: "126 cm", width: "58 cm",
    footBase: undefined, weight: "88,5 kg", stock: 4,
    description: "Très joli vase Médicis classique en fonte posé sur une base. Cet ensemble peut trouver aisément sa place dans votre jardin et sera extrèmement élégant et décoratif. Il peut aussi decorer une entrée ou se mettre à l'interieur de votre maison. Possibilité de planter grâce à un évacuation d'eau.",
    img: "/clients/ines-garden/products/vases-medicis/4-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "134-vase-medicis-en-fonte-cannele-bronze-vert", id: "134", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 100 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP38H bv",
    price: 1690, height: "100 cm", width: "68 cm",
    footBase: "36 cm", weight: "128 kg", stock: 4,
    description: "Inspiré du célèbre Vase Médicis , chef-d’œuvre antique du Ier siècle av. J.-C. exposé à la Galerie des Offices à Florence, ce vase reprend les codes esthétiques qui ont marqué plus de deux millénaires d’art décoratif. Réapparu à la Renaissance dans les collections de la puissante famille Médicis, ce modèle est devenu un symbole de prestige et d’élégance dans les jardins princiers européens. Les cannelures verticales , héritées des colonnes grecques et romaines, apportent relief et noblesse à la silhouette du vase, en soulignant son caractère classique. Reproduit en fonte au fil des siècles pour orner parcs, demeures et entrées majestueuses, le vase Médicis demeure aujourd’hui une pièce emblématique, à la fois décorative et intemporelle.",
    img: "/clients/ines-garden/products/vases-medicis/none-vase-medicis-en-fonte-cannele-bronze-vert-1.jpeg",
  },
  {
    slug: "7-vase-medicis-en-fonte-bronze-vert", id: "7", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 140 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP245C+B76 bv",
    price: 1850, height: "140 cm", width: "56 cm",
    footBase: undefined, weight: "130 kg", stock: 10,
    description: "Grand vase Médicis classique en fonte posé sur sa base pour le mettre en valeur. Cette paire de vases Médicis en fonte décore très élégamment un grand jardin ou une entrée.. Son volume très important lui permet de recevoir de grosse plantes qui ont besoin d'espace.",
    img: "/clients/ines-garden/products/vases-medicis/7-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "58-vase-medicis-en-fonte-bronze-vert", id: "58", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 108 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP245D bv",
    price: 1990, height: "108 cm", width: "80 cm",
    footBase: "48 cm", weight: "160 kg", stock: 3,
    description: "Très gros vase Médicis classique en fonte. Ce vase peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif grâce à se taille imposante. Il peut aussi décorer une entrée. Possibilité de planter grâce à une évacuation d'eau et à un trés gros volume de terre.",
    img: "/clients/ines-garden/products/vases-medicis/58-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "56-vase-medicis-en-fonte-noir", id: "56", category: "vases-medicis",
    name: "Vase Médicis · Noir 108 cm", baseName: "Vase Médicis en fonte",
    color: "Noir", swatch: "#242220", ref: "HSP243D n",
    price: 1990, height: "108 cm", width: "80 cm",
    footBase: "48 cm", weight: "180 kg", stock: 3,
    description: "Très gros vase Médicis classique en fonte. Ce vase peut trouver aisément sa place dans votre jardin et sera extrêmement élégant et décoratif grâce à sa taille imposante. Il peut aussi décorer une entrée. Possibilité de planter grâce à une évacuation d'eau et à un trés gros volume de terre.",
    img: "/clients/ines-garden/products/vases-medicis/56-vase-medicis-en-fonte-noir-1.jpg",
  },
  {
    slug: "59-vase-medicis-en-fonte-pierre", id: "59", category: "vases-medicis",
    name: "Vase Médicis · Pierre 151 cm", baseName: "Vase Médicis en fonte",
    color: "Pierre", swatch: "#cabfae", ref: "HSP13D p",
    price: 2900, height: "151 cm", width: "105 cm",
    footBase: undefined, weight: "350 kg", stock: 2,
    description: "Très gros vase Médicis classique en fonte. Cet pièce unique peut trouver aisément sa place dans votre jardin et sera extrêmement élégante et décorative. Elle peut aussi décorer une entrée. Possibilité de planter grâce à une évacuation d'eau. DISPONIBLE AUSSI COULEUR : NOIR",
    img: "/clients/ines-garden/products/vases-medicis/59-vase-medicis-en-fonte-pierre-1.jpg",
  },
  {
    slug: "8-vase-medicis-en-fonte-patine-bronze-vert", id: "8", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert patiné 194,5 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert patiné", swatch: "#586a4f", ref: "HSP245D+B75 bv",
    price: 4900, height: "194,5 cm", width: "80 cm",
    footBase: undefined, weight: "360 kg", stock: 2,
    description: "Très grand vase Médicis classiques en fonte posé sur sa base pour le mettre en valeur.",
    img: "/clients/ines-garden/products/vases-medicis/8-vase-medicis-en-fonte-patine-bronze-vert-1.jpg",
  },
  {
    slug: "60-vase-medicis-en-fonte-bronze-vert", id: "60", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 155 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP243A bv",
    price: 7900, height: "155 cm", width: "122 cm",
    footBase: undefined, weight: "540 kg", stock: null,
    description: "Réédition d'un très grand Vase Médicis en fonte classique unique au monde.",
    img: "/clients/ines-garden/products/vases-medicis/60-vase-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "11-vase-medicis-en-fonte-bronze-vert", id: "11", category: "vases-medicis",
    name: "Vase Médicis · Bronze-vert 280 cm", baseName: "Vase Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP243A+B74 bv",
    price: 14900, height: "280 cm", width: "122 cm",
    footBase: undefined, weight: "980 kg", stock: null,
    description: "Très grand vase Médicis classiques en fonte posé sur sa base pour le mettre en valeur.",
    img: "/clients/ines-garden/products/vases-medicis/11-vase-medicis-en-fonte-bronze-vert-1.jpeg",
  },
  {
    slug: "62-vasque-medicis-en-fonte-gris", id: "62", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 27,5 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP318 bv",
    price: 175, height: "27,5 cm", width: "38 cm",
    footBase: "15 cm", weight: "14 kg", stock: 14,
    description: "Magnifique petite vasque Médicis pour décorer un jardin ou une entrée. Il est possible de planter des fleurs dans ce vase grâce à l'évacuation d'eau.",
    img: "/clients/ines-garden/products/vasques-medicis/62-vasque-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "70-vasque-medicis-en-fonte-bronze-vert", id: "70", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 35,5 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP317 bv",
    price: 330, height: "35,5 cm", width: "46,5 cm",
    footBase: "19 cm", weight: "24 kg", stock: 23,
    description: "Magnifique petite vasque Médicis pour décorer un jardin ou une entrée. Il est possible de planter des fleurs dans ce vase grâce à l'évacuation d'eau.",
    img: "/clients/ines-garden/products/vasques-medicis/70-vasque-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "63-vasque-medicis-sur-colonne-bronze-vert", id: "63", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 80 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP43 bv",
    price: 420, height: "80 cm", width: "42 cm",
    footBase: undefined, weight: "29 kg", stock: 6,
    description: "Magnifique vasque style Médicis avec comme pied une colonne qui lui donne beaucoup plus de valeur et qui lui permet de décorer un jardin ou une entrée. Il est possible de planter des fleurs dans ce vase grâce à l'évacuation d'eau.",
    img: "/clients/ines-garden/products/vasques-medicis/63-vasque-medicis-sur-colonne-bronze-vert-1.jpg",
  },
  {
    slug: "68-vasque-fontaine-en-fonte-bronze-vert", id: "68", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 92 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSU31 bv",
    price: 450, height: "92 cm", width: "48 cm",
    footBase: undefined, weight: "32 kg", stock: 6,
    description: "Magnifique vasque avec comme pied une colonne qui lui donne beaucoup plus de valeur et qui lui permet de décorer un jardin ou une entrée. Il n'y a aucune evacuation d'eau car cela sert pour un stockage d'eau pour les oiseaux.",
    img: "/clients/ines-garden/products/vasques-medicis/68-vasque-fontaine-oiseaux-bronze-vert-1.jpg",
  },
  {
    slug: "73-vasque-medicis-en-fonte-gris", id: "73", category: "vasques-medicis",
    name: "Vasque Médicis · Gris 45 cm", baseName: "Vasque Médicis en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP180 g",
    price: 650, height: "45 cm", width: "63 cm",
    footBase: undefined, weight: "41 kg", stock: 4,
    description: "Très jolie vasque de style Medicis en fonte pour décorer votre jardin. Cette vasque peut trouver sa place sur une terrasse, se poser sur des piliers d'entrée de propriété, au bord d'une piscine. L'idéal est de la garnie d'un buis persistant et d'y ajouter des fleurs pour apporter de la couleur en été.",
    img: "/clients/ines-garden/products/vasques-medicis/73-vasque-medicis-en-fonte-gris-1.jpg",
  },
  {
    slug: "72-vasque-medicis-en-fonte-bronze-vert", id: "72", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 45 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP180 bv",
    price: 690, height: "45 cm", width: "63 cm",
    footBase: undefined, weight: "41 kg", stock: 20,
    description: "Très jolie vasque de style Medicis en fonte pour décorer votre jardin. Cette vasque peut trouver sa place sur une terrasse, se poser sur des piliers d'entrée de propriété, au bord d'une piscine. L'idéal est de la garnie d'un buis persistant et d'y ajouter des fleurs pour apporter de la couleur en été.",
    img: "/clients/ines-garden/products/vasques-medicis/72-vasque-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "74-vasque-medicis-en-fonte-bronze-vert", id: "74", category: "vasques-medicis",
    name: "Vasque Médicis · Gris 55 cm", baseName: "Vasque Médicis en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP316 g",
    price: 850, height: "55 cm", width: "75 cm",
    footBase: undefined, weight: "70 kg", stock: 12,
    description: "Très belle vasque style Médicis en fonte. Modèle assez imposant et très élégant. L'agrémenter d'un buis boule qui restera à l'année et apporter de la couleur au printemps avec des fleurs saisonnières et surtout des plantes retombantes genre surfinia ou géraniums lierres.",
    img: "/clients/ines-garden/products/vasques-medicis/74-vasque-medicis-en-fonte-gris-1.jpg",
  },
  {
    slug: "75-vasque-medicis-en-fonte-bronze-vert", id: "75", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 55 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP316 bv",
    price: 900, height: "55 cm", width: "75 cm",
    footBase: undefined, weight: "70 kg", stock: 10,
    description: "Très belle vasque style Médicis en fonte. Modèle assez imposant et très élégant. L'agrémenter d'un buis boule qui restera à l'année et apporter de la couleur au printemps avec des fleurs saisonnières et surtout des plantes retombantes genre surfinia ou géraniums lierres.",
    img: "/clients/ines-garden/products/vasques-medicis/75-vasque-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "77-vasque-medicis-en-fonte-bronze-vert", id: "77", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 126 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP149B+B45 bv",
    price: 2770, height: "126 cm", width: "106 cm",
    footBase: undefined, weight: "207 kg", stock: 1,
    description: "Magnifique vasque sur base qui convient très bien pour placer au milieu d'une pelouse. Contenant un gros volume de terre elle accepte un arbuste persistant qui restera en place toute l'année. Au printemps, rajouter quelques fleurs retombantes style surfinia ou géranium lierres pour donner de la couleur. Cette pièce est d'une grande élégance et met véritablement un jardin en valeur.",
    img: "/clients/ines-garden/products/vasques-medicis/77-vasque-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "78-vasque-medicis-en-fonte-bronze-marron", id: "78", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-marron 154 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-marron", swatch: "#6b4c34", ref: "HSP291+B44 bm",
    price: 2900, height: "154 cm", width: "131 cm",
    footBase: undefined, weight: "390 kg", stock: 3,
    description: "Magnifique vasque sur base qui convient très bien pour placer au milieu d'une pelouse. Contenant un gros volume de terre elle accepte un arbuste persistant qui restera en place toute l'année. Au printemps, rajouter quelques fleurs retombantes style surfinia ou géranium lierres pour donner de la couleur. Cette pièce est d'une grande élégance et met véritablement un jardin en valeur.",
    img: "/clients/ines-garden/products/vasques-medicis/78-vasque-medicis-en-fonte-bronze-marron-1.jpg",
  },
  {
    slug: "79-vasque-medicis-en-fonte-bronze-vert", id: "79", category: "vasques-medicis",
    name: "Vasque Médicis · Bronze-vert 216 cm", baseName: "Vasque Médicis en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP244A+B74 bv",
    price: 14800, height: "216 cm", width: "152 cm",
    footBase: undefined, weight: "840 kg", stock: null,
    description: "Magnifique Vasques style Médicis poser sur imposant socle pour agrémenter votre parc ou jardin avec un volume de terre trés important qui permet de planter se que vous souhaitez. Cette vasque serait idéal pour décorer une entrée de chateau. dimension de la vasque: -hauteur = 100cm , largeur = 152cm dimension du socle : -hauteur = 106cm , largeur = 96cm",
    img: "/clients/ines-garden/products/vasques-medicis/79-vasque-medicis-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "102-tete-de-cheval-en-fonte-bronze-vert", id: "102", category: "tetes-de-cheval",
    name: "Tête de cheval · Bronze-vert 50 cm", baseName: "Tête de cheval en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "Tête de cheval",
    price: 570, height: "50 cm", width: "25 cm",
    footBase: undefined, weight: "25 kg", stock: 2,
    description: "Cette tête de cheval en fonte est une création exclusive \"des Jardins d'Inès\". Elle est idéale pour décorer une écurie. Elle s'accroche très facilement au mur avec un piton à pas de vis. On peut lui fixer un crochet sous la ganache pour suspendre une jardinière de fleur ou, plus utile, des licols.",
    img: "/clients/ines-garden/products/tetes-de-cheval/102-tete-de-cheval-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "107-statue-en-fonte-4-saisons-blanc", id: "107", category: "statues",
    name: "Statue 4 saisons · Blanc 150 cm", baseName: "Statue en fonte 4 saisons",
    color: "Blanc", swatch: "#eeeae1", ref: "HS111D",
    price: 3500, height: "150 cm", width: "40 cm",
    footBase: undefined, weight: "200 kg", stock: null,
    description: "Magnifique statue en fonte représentant le hiver des 4 saisons.",
    img: "/clients/ines-garden/products/statues/107-statue-en-fonte-4-saisons-blanc-1.jpg",
  },
  {
    slug: "108-statue-en-fonte-4-saisons-blanc", id: "108", category: "statues",
    name: "Statue 4 saisons · Blanc 150 cm", baseName: "Statue en fonte 4 saisons",
    color: "Blanc", swatch: "#eeeae1", ref: "HS111B",
    price: 3500, height: "150 cm", width: "40 cm",
    footBase: undefined, weight: "200 kg", stock: null,
    description: "Magnifique statue en fonte représentant le hiver des 4 saisons.",
    img: "/clients/ines-garden/products/statues/108-statue-en-fonte-4-saisons-blanc-1.jpg",
  },
  {
    slug: "106-statue-en-fonte-4-saisons-blanc", id: "106", category: "statues",
    name: "Statue 4 saisons · Blanc 150 cm", baseName: "Statue en fonte 4 saisons",
    color: "Blanc", swatch: "#eeeae1", ref: "HS111C",
    price: 3500, height: "150 cm", width: "40 cm",
    footBase: undefined, weight: "200 kg", stock: null,
    description: "Magnifique statue en fonte représentant le hiver des 4 saisons.",
    img: "/clients/ines-garden/products/statues/106-statue-en-fonte-4-saisons-blanc-1.jpg",
  },
  {
    slug: "109-statue-en-fonte-4-saisons-blanc", id: "109", category: "statues",
    name: "Statue 4 saisons · Blanc 150 cm", baseName: "Statue en fonte 4 saisons",
    color: "Blanc", swatch: "#eeeae1", ref: "HS111A",
    price: 3500, height: "150 cm", width: "40 cm",
    footBase: undefined, weight: "200 kg", stock: null,
    description: "Magnifique statue en fonte représentant le hiver des 4 saisons.",
    img: "/clients/ines-garden/products/statues/109-statue-en-fonte-4-saisons-blanc-1.jpg",
  },
  {
    slug: "113-statue-en-fonte-4-saisons-pierre", id: "113", category: "statues",
    name: "Statue 4 saisons · Pierre 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Pierre", swatch: "#cabfae", ref: "HS111C+B94 p",
    price: 6500, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant le printemps des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/113-statue-en-fonte-4-saisons-pierre-1.jpg",
  },
  {
    slug: "110-statue-en-fonte-4-saisons-pierre", id: "110", category: "statues",
    name: "Statue 4 saisons · Pierre 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Pierre", swatch: "#cabfae", ref: "HS111A+B94 p",
    price: 6500, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'hiver des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/110-statue-en-fonte-4-saisons-pierre-1.jpg",
  },
  {
    slug: "111-statue-en-fonte-4-saisons-pierre", id: "111", category: "statues",
    name: "Statue 4 saisons · Pierre 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Pierre", swatch: "#cabfae", ref: "HS111D+B94 p",
    price: 6500, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'été des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/111-statue-en-fonte-4-saisons-pierre-1.jpg",
  },
  {
    slug: "112-statue-en-fonte-4-saisons-pierre", id: "112", category: "statues",
    name: "Statue 4 saisons · Pierre 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Pierre", swatch: "#cabfae", ref: "HS111B+B94 p",
    price: 6500, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'automne des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/112-statue-en-fonte-4-saisons-pierre-1.jpg",
  },
  {
    slug: "114-statue-en-fonte-4-saisons-bronze-bleute", id: "114", category: "statues",
    name: "Statue 4 saisons · Bronze-bleuté 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Bronze-bleuté", swatch: "#46566a", ref: "HS111C+Base",
    price: 6510, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'hiver des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/114-statue-en-fonte-4-saisons-bronze-bleute-1.jpg",
  },
  {
    slug: "115-statue-en-fonte-4-saisons-bronze-bleute", id: "115", category: "statues",
    name: "Statue 4 saisons · Bronze-bleuté 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Bronze-bleuté", swatch: "#46566a", ref: "HS111D+Base",
    price: 6510, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'hiver des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/115-statue-en-fonte-4-saisons-bronze-bleute-1.jpg",
  },
  {
    slug: "116-statue-en-fonte-4-saisons-bronze-bleute", id: "116", category: "statues",
    name: "Statue 4 saisons · Bronze-bleuté 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Bronze-bleuté", swatch: "#46566a", ref: "HS111A+Base",
    price: 6510, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'hiver des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/116-statue-en-fonte-4-saisons-bronze-bleute-1.jpg",
  },
  {
    slug: "117-statue-en-fonte-4-saisons-bronze-bleute", id: "117", category: "statues",
    name: "Statue 4 saisons · Bronze-bleuté 233 cm", baseName: "Statue en fonte 4 saisons",
    color: "Bronze-bleuté", swatch: "#46566a", ref: "HS111B+Base",
    price: 6510, height: "233 cm", width: "63 cm",
    footBase: undefined, weight: "390 kg", stock: null,
    description: "Magnifique statue en fonte représentant l'hiver des 4 saisons sur un très beau socle.",
    img: "/clients/ines-garden/products/statues/117-statue-en-fonte-4-saisons-bronze-bleute-1.jpg",
  },
  {
    slug: "81-bac-a-oranger-en-fonte-bronze-vert", id: "81", category: "bacs-a-oranger",
    name: "Bac à oranger · Bronze-vert 52 cm", baseName: "Bac à oranger en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP363 bv",
    price: 510, height: "52 cm", width: "34,5 cm",
    footBase: undefined, weight: "39 kg", stock: 10,
    description: "Bac à Orangers en fonte : Décoré d'une croix avec des cercles au centre de chaque face, une pomme de pin est sculptée sur chaque pied du bac à oranger. Solide, le bac à oranger touche le sol grâce à ses pieds en boule. Sa finition est harmonieuse et il se fond parfaitement dans le décor. Ces bacs en fonte sont d'une solidité exceptionnelle et résiste très bien à tous les petits caprices de la météo.",
    img: "/clients/ines-garden/products/bacs-a-oranger/81-bac-a-oranger-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "83-bac-a-oranger-bronze-vert", id: "83", category: "bacs-a-oranger",
    name: "Bac à oranger · Bronze-vert 79 cm", baseName: "Bac à oranger en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP362 bv",
    price: 2500, height: "79 cm", width: "63,5 cm",
    footBase: undefined, weight: "165 kg", stock: 2,
    description: "Superbe Bacs à Orangers : Ces caisses en fonte d'un très gros volume et d'une solidité exceptionnelle mettent en valeur aussi bien un parc, un jardin, un salon, une terrasse, qu'un site urbain.",
    img: "/clients/ines-garden/products/bacs-a-oranger/83-bac-a-oranger-bronze-vert-1.jpg",
  },
  {
    slug: "84-jardiniere-en-fonte-bronze-marron", id: "84", category: "jardinieres",
    name: "Jardinière · Bronze-marron 14 cm", baseName: "Jardinière en fonte",
    color: "Bronze-marron", swatch: "#6b4c34", ref: "HSP17B bm",
    price: 50, height: "14 cm", width: "13 cm",
    footBase: undefined, weight: "5 kg", stock: 11,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/84-jardiniere-en-fonte-bronze-marron-1.jpg",
  },
  {
    slug: "86-jardiniere-en-fonte-gris", id: "86", category: "jardinieres",
    name: "Jardinière · Gris 14 cm", baseName: "Jardinière en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP17B g",
    price: 50, height: "14 cm", width: "13 cm",
    footBase: undefined, weight: "5 kg", stock: 5,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/86-jardiniere-en-fonte-gris-1.jpg",
  },
  {
    slug: "85-jardiniere-en-fonte-pierre", id: "85", category: "jardinieres",
    name: "Jardinière · Pierre 14 cm", baseName: "Jardinière en fonte",
    color: "Pierre", swatch: "#cabfae", ref: "HSP17B p",
    price: 50, height: "14 cm", width: "13 cm",
    footBase: undefined, weight: "5 kg", stock: 6,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/85-jardiniere-en-fonte-pierre-1.jpg",
  },
  {
    slug: "90-jardiniere-en-fonte-bronze-vert", id: "90", category: "jardinieres",
    name: "Jardinière · Bronze-vert 12 cm", baseName: "Jardinière en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP499 bv",
    price: 55, height: "12 cm", width: "15 cm",
    footBase: undefined, weight: "7 kg", stock: 1,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/90-jardiniere-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "87-jardiniere-en-fonte-bronze-marron", id: "87", category: "jardinieres",
    name: "Jardinière · Bronze-marron 12 cm", baseName: "Jardinière en fonte",
    color: "Bronze-marron", swatch: "#6b4c34", ref: "HSP499 bm",
    price: 55, height: "12 cm", width: "15 cm",
    footBase: undefined, weight: "7 kg", stock: 6,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/87-jardiniere-en-fonte-bronze-marron-1.jpg",
  },
  {
    slug: "88-jardiniere-en-fonte-gris", id: "88", category: "jardinieres",
    name: "Jardinière · Gris 12 cm", baseName: "Jardinière en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP499 g",
    price: 55, height: "12 cm", width: "15 cm",
    footBase: undefined, weight: "7 kg", stock: 6,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/88-jardiniere-en-fonte-gris-1.jpg",
  },
  {
    slug: "89-jardiniere-en-fonte-pierre", id: "89", category: "jardinieres",
    name: "Jardinière · Pierre 12 cm", baseName: "Jardinière en fonte",
    color: "Pierre", swatch: "#cabfae", ref: "HSP499 p",
    price: 55, height: "12 cm", width: "15 cm",
    footBase: undefined, weight: "7 kg", stock: 6,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/89-jardiniere-en-fonte-pierre-1.jpg",
  },
  {
    slug: "91-jardiniere-en-fonte-gris", id: "91", category: "jardinieres",
    name: "Jardinière · Gris 12 cm", baseName: "Jardinière en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP470 g",
    price: 60, height: "12 cm", width: "13 cm",
    footBase: undefined, weight: "7 kg", stock: 6,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/91-jardiniere-en-fonte-gris-1.jpg",
  },
  {
    slug: "93-jardiniere-en-fonte-bronze-vert", id: "93", category: "jardinieres",
    name: "Jardinière · Bronze-vert 12 cm", baseName: "Jardinière en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP470 bv",
    price: 60, height: "12 cm", width: "13 cm",
    footBase: undefined, weight: "7 kg", stock: 3,
    description: "Elégante jardinière en fonte de forme originale. A poser sur un rebord de fenêtre, un mur en pierre ou sur une terrasse.",
    img: "/clients/ines-garden/products/jardinieres/93-jardiniere-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "99-jardiniere-en-fonte-bronze-vert", id: "99", category: "jardinieres",
    name: "Jardinière · Bronze-vert 30 cm", baseName: "Jardinière en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSP104A bv",
    price: 270, height: "30 cm", width: "40 cm",
    footBase: undefined, weight: "33 kg", stock: 6,
    description: "Magnifique jardinière en fonte a angle 90 degrés, idéal pour mettre dans l'angle d'une fenêtre ou d'un mur directement posé au sol.",
    img: "/clients/ines-garden/products/jardinieres/99-jardiniere-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "100-jardiniere-en-fonte-gris", id: "100", category: "jardinieres",
    name: "Jardinière · Gris 25 cm", baseName: "Jardinière en fonte",
    color: "Gris", swatch: "#8b8a84", ref: "HSP97E g",
    price: 360, height: "25 cm", width: "26 cm",
    footBase: undefined, weight: "43 kg", stock: 5,
    description: "Somptueuse et imposante cette jardinière en fonte trouvera parfaitement sa place dans une grande demeure sur les rebords des fenêtres ou sur un mur en pierre. Pouvant contenir beaucoup de terre et possède une évacuation d'eau pour planter.",
    img: "/clients/ines-garden/products/jardinieres/100-jardiniere-en-fonte-gris-1.jpg",
  },
  {
    slug: "80-salon-de-jardin-noir", id: "80", category: "salons-de-jardin",
    name: "Salon de jardin · Noir", baseName: "Salon de jardin en fonte",
    color: "Noir", swatch: "#242220", ref: "HSP001 bv",
    price: 1900, height: "0 cm", width: "0 cm",
    footBase: undefined, weight: undefined, stock: 1,
    description: "Salon de jardin en fonte avec table et chaises style ancien. Robustes et résistants, il passeront les intempéries et le beau temps à merveille.",
    img: "/clients/ines-garden/products/salons-de-jardin/80-salon-de-jardin-en-fonte-noir-1.jpg",
  },
  {
    slug: "103-fontaine-en-fonte-bronze-vert", id: "103", category: "fontaines",
    name: "Fontaine · Bronze-vert 142 cm", baseName: "Fontaine en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSF3",
    price: 1100, height: "142 cm", width: "60 cm",
    footBase: undefined, weight: "82 kg", stock: 3,
    description: "Très jolie fontaine en fonte avec deux bacs de réception pyramidaux. Prévue pour une installation d'un tuyau d'arrivée d'eau. Peu également s'utiliser pour mettre des fleurs retombantes.",
    img: "/clients/ines-garden/products/fontaines/103-fontaine-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "105-fontaine-en-fonte-bronze-vert", id: "105", category: "fontaines",
    name: "Fontaine · Bronze-vert 229 cm", baseName: "Fontaine en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSF1",
    price: 2900, height: "229 cm", width: "113 cm",
    footBase: undefined, weight: "220 kg", stock: 2,
    description: "Très jolie fontaine en fonte avec trois bacs de réception pyramidaux. Prévue pour une installation d'un tuyau d'arrivée d'eau. Peu également s'utiliser pour mettre des fleurs retombantes.",
    img: "/clients/ines-garden/products/fontaines/105-fontaine-en-fonte-bronze-vert-1.jpg",
  },
  {
    slug: "121-fontaine-en-fonte-3-etages-bronze-vert", id: "121", category: "fontaines",
    name: "Fontaine · Bronze-vert 362 cm", baseName: "Fontaine en fonte",
    color: "Bronze-vert", swatch: "#4c5a42", ref: "HSF30",
    price: 11690, height: "362 cm", width: "146 cm",
    footBase: undefined, weight: "800 kg", stock: null,
    description: "Cette magnifique fontaine très imposante et composé de 3 étages va pouvoir se mettre dans vos plus grands bassins. C'est une très belle pièces majestueuse de plus de 3m de hauteur.",
    img: "/clients/ines-garden/products/fontaines/121-fontaine-en-fonte-3-etages-bronze-vert-1.jpeg",
  },
];
