/* Libellés de l'outil de devis, dans les deux langues du site.

   Volontairement à part de `lib/i18n.ts` : ce dictionnaire-là sert le SITE
   PUBLIC (660 lignes, chargé par chaque vitrine). L'outil de devis est un
   espace protégé, ouvert par une poignée de gens ; son vocabulaire n'a rien à
   faire dans le bundle d'une page vitrine. */

import type { Lang } from "../i18n";

export type DocStrings = typeof FR;

const FR = {
  title: "Devis & factures",
  lead: (trade: string) => `${trade} — vos documents, à vos couleurs et à vos tarifs.`,
  tabs: { quote: "Devis", invoice: "Factures" },
  newQuote: "Nouveau devis",
  newInvoice: "Nouvelle facture",
  creating: "Création…",

  // Liste
  colNumber: "Numéro",
  colDate: "Date",
  colClient: "Client",
  colTotal: "Total TTC",
  colStatus: "Statut",
  emptyQuoteT: "Aucun devis",
  emptyQuoteD: "Créez-en un : les prestations de votre carte sont déjà chargées, il n'y a qu'à choisir.",
  emptyInvoiceT: "Aucune facture",
  emptyInvoiceD: "Une facture naît d'un devis accepté, ou se crée directement.",
  noClient: "Sans destinataire",

  // Éditeur
  back: "Retour à la liste",
  clientTitle: "Destinataire",
  clientName: "Nom",
  clientEmail: "E-mail",
  clientPhone: "Téléphone",
  clientAddress: "Adresse",
  clientPostal: "Code postal",
  clientCity: "Ville",
  pickContact: "Reprendre un client connu",
  pickContactHint: "Les personnes qui ont déjà appelé votre standardiste.",

  linesTitle: "Lignes",
  addLine: "Ligne libre",
  addDiscount: "Remise",
  catalogTitle: "Votre carte",
  catalogHint: "Un clic pose la ligne, prix compris.",
  catalogToQuote: "à chiffrer",
  colDesignation: "Désignation",
  colQty: "Qté",
  colUnit: "P.U. HT",
  colTax: "Taxe",
  colLineTotal: "Total HT",
  discountLine: "Remise commerciale",
  removeLine: "Retirer cette ligne",
  noLines: "Aucune ligne. Choisissez une prestation dans votre carte, ou ajoutez une ligne libre.",

  notesTitle: "Notes",
  notesHint: "Ce que vous voulez dire au client — visible sur le document.",

  subtotal: "Sous-total HT",
  discount: "Remise",
  totalHT: "Total HT",
  totalTTC: "Total TTC",

  dates: "Dates",
  issuedOn: "Émis le",
  validUntil: "Valable jusqu'au",
  dueOn: "À régler avant le",

  save: "Enregistrer",
  saving: "Enregistrement…",
  saved: "Enregistré",
  unsaved: "Modifications non enregistrées",
  leaveConfirm: "Des modifications ne sont pas enregistrées. Quitter quand même ?",
  backToSpace: "Votre espace",
  print: "Imprimer / PDF",
  convert: "Créer la facture",
  converting: "Création…",
  del: "Supprimer",
  delConfirm: "Supprimer définitivement ce document ?",
  statusLabel: "Statut",
  convertedFrom: "Établie d'après le devis",

  // Document
  quoteWord: "Devis",
  invoiceWord: "Facture",
  issuerWord: "Émetteur",
  recipientWord: "Client",
  numberWord: "N°",
  signature: "Bon pour accord — date et signature",
  page: "Document établi par",

  errorSave: "Enregistrement impossible.",
  errorLoad: "Données indisponibles.",

  /* ══════════════════════════════════════════════════════════════════════════
     L'APPLICATION À ONGLETS (portage de ~/devis_app, 2026-09-04).
     ══════════════════════════════════════════════════════════════════════════ */

  tab: {
    editor: "Devis en cours",
    quotes: "Mes devis",
    invoices: "Factures",
    clients: "Clients",
    catalog: "Catalogue",
    dashboard: "Tableau de bord",
    settings: "Réglages",
  },

  units: {
    unite: "unité", heure: "heure", jour: "jour", forfait: "forfait",
    m2: "m²", ml: "ml", kg: "kg",
  },
  unitsShort: {
    unite: "u", heure: "h", jour: "j", forfait: "forf.",
    m2: "m²", ml: "ml", kg: "kg",
  },
  colUnit2: "Unité",

  /* ── Enregistrement automatique ────────────────────────────────────────── */
  auto: {
    idle: "Enregistré",
    pending: "Modifications en attente…",
    saving: "Enregistrement…",
    savedAt: (time: string) => `Enregistré à ${time}`,
    failed: "Enregistrement impossible — vos saisies restent à l'écran.",
    retry: "Réessayer",
  },

  /* ── Dictée ────────────────────────────────────────────────────────────── */
  voice: {
    start: "Dicter le devis",
    stop: "Terminer la dictée",
    listening: "Je vous écoute…",
    transcribing: "Transcription…",
    analysing: "Analyse…",
    hint: "Dictez vos prestations : « pose de deux radiateurs à quatre cent vingt euros pièce, plus une journée de main-d'œuvre ».",
    heard: "Entendu :",
    applied: (n: number) => `${n} ligne${n > 1 ? "s" : ""} ajoutée${n > 1 ? "s" : ""}.`,
    replaced: (n: number) => `Devis remplacé par ${n} ligne${n > 1 ? "s" : ""}.`,
    nothing: "Rien de chiffrable dans cette dictée. Reformulez en nommant la prestation et son prix.",
    denied: "Micro refusé. Autorisez l'accès au micro dans votre navigateur, puis réessayez.",
    unsupported: "Ce navigateur ne sait pas enregistrer le micro.",
    error: "La dictée n'a pas abouti.",
    speakToggle: "Confirmation parlée",
    examples: "Exemples de dictée",
    ex1: "« Deux heures de main-d'œuvre à soixante euros. »",
    ex2: "« Ajoute une remise de dix pour cent. »",
    ex3: "« Recommence, efface tout. »",
  },

  /* ── Listes de documents ───────────────────────────────────────────────── */
  list: {
    search: "Rechercher un numéro, un client…",
    all: "Tous",
    open: "Ouvrir",
    duplicate: "Dupliquer",
    none: "Aucun document ne correspond.",
    totalRow: (n: number, amount: string) => `${n} document${n > 1 ? "s" : ""} · ${amount}`,
  },

  /* ── Clients ───────────────────────────────────────────────────────────── */
  clients: {
    title: "Fichier client",
    add: "Nouveau client",
    search: "Nom, société, téléphone, e-mail",
    company: "Société",
    siret: "SIRET",
    notesLabel: "Notes internes",
    fromVoice: "Rencontré au téléphone",
    fromPortal: "Saisi ici",
    save: "Enregistrer le client",
    del: "Supprimer la fiche",
    delConfirm: "Supprimer cette fiche ? Le journal, lui, garde la trace des faits.",
    useInQuote: "Mettre sur le devis",
    emptyT: "Aucun client",
    emptyD: "Ajoutez-en un, ou laissez la standardiste les inscrire au fil des appels.",
    docsCount: (n: number) => `${n} document${n > 1 ? "s" : ""}`,
    needName: "Indiquez au moins un nom ou une société.",
  },

  /* ── Catalogue ─────────────────────────────────────────────────────────── */
  cat: {
    title: "Votre catalogue",
    lead: "Semé depuis votre vitrine au premier accès. À partir de là, il est à vous.",
    addItem: "Nouvelle prestation",
    addCategory: "Nouveau rayon",
    noCategory: "Sans rayon",
    itemName: "Prestation",
    price: "Prix HT",
    purchase: "Prix d'achat",
    margin: "Marge",
    toQuote: "À chiffrer",
    toQuoteHint: "Prestation sans prix affiché : elle se chiffre au cas par cas.",
    categoryName: "Nom du rayon",
    color: "Couleur",
    delItem: "Supprimer la prestation",
    delCategory: "Supprimer le rayon",
    delCategoryConfirm: "Supprimer ce rayon ? Ses prestations sont conservées et retombent dans « sans rayon ».",
    emptyT: "Catalogue vide",
    emptyD: "Votre vitrine n'affiche aucun prix exploitable : composez votre catalogue à la main.",
    count: (n: number) => `${n} prestation${n > 1 ? "s" : ""}`,
  },

  /* ── Tableau de bord ───────────────────────────────────────────────────── */
  dash: {
    title: "Votre activité",
    lead: "Ce que vos devis ont produit, sur les douze derniers mois.",
    quoted: "Devis émis",
    accepted: "Devis acceptés",
    conversion: "Taux d'acceptation",
    invoiced: "Facturé",
    paid: "Encaissé",
    outstanding: "Reste à encaisser",
    avgQuote: "Devis moyen",
    byMonth: "Mois par mois",
    topItems: "Ce qui se vend",
    topEmpty: "Rien de vendu pour l'instant.",
    noData: "Pas encore de document : les chiffres apparaîtront ici.",
    monthQuotes: "Devis",
    monthInvoices: "Factures",
  },

  /* ── Réglages ──────────────────────────────────────────────────────────── */
  set: {
    title: "Réglages du document",
    lead: "Ce que votre vitrine ne dit pas, et qu'un document comptable exige. Un champ laissé vide reprend la valeur de votre vitrine.",
    identity: "Identité",
    payment: "Paiement",
    legal: "Mentions",
    inherited: (value: string) => `Vitrine : ${value}`,
    companyName: "Raison sociale",
    legalForm: "Forme juridique",
    siret: "SIRET",
    vatNumber: "N° de TVA intracommunautaire",
    address: "Adresse",
    postalCode: "Code postal",
    city: "Ville",
    country: "Pays",
    phone: "Téléphone",
    email: "E-mail",
    website: "Site",
    logoUrl: "Logo (URL)",
    iban: "IBAN",
    bic: "BIC",
    paymentMethod: "Moyen de paiement accepté",
    paymentDays: "Délai de paiement (jours)",
    validityDays: "Validité d'un devis (jours)",
    taxRateDefault: "Taux de taxe par défaut (%)",
    footerNotes: "Mentions ajoutées en pied de document",
    footerHint: "Elles s'ajoutent aux mentions légales, elles ne les remplacent pas.",
    insuranceLabel: "Assurance",
    insuranceDetail: "Détail de l'assurance",
    save: "Enregistrer les réglages",
    saved: "Réglages enregistrés",
  },
};

const EN: DocStrings = {
  title: "Quotes & invoices",
  lead: (trade: string) => `${trade} — your documents, in your colours and at your prices.`,
  tabs: { quote: "Quotes", invoice: "Invoices" },
  newQuote: "New quote",
  newInvoice: "New invoice",
  creating: "Creating…",

  colNumber: "Number",
  colDate: "Date",
  colClient: "Client",
  colTotal: "Total",
  colStatus: "Status",
  emptyQuoteT: "No quotes yet",
  emptyQuoteD: "Create one — your price list is already loaded, you only have to pick.",
  emptyInvoiceT: "No invoices yet",
  emptyInvoiceD: "An invoice comes from an accepted quote, or is created directly.",
  noClient: "No recipient",

  back: "Back to list",
  clientTitle: "Recipient",
  clientName: "Name",
  clientEmail: "Email",
  clientPhone: "Phone",
  clientAddress: "Address",
  clientPostal: "Postcode",
  clientCity: "City",
  pickContact: "Reuse a known client",
  pickContactHint: "People who have already called your receptionist.",

  linesTitle: "Lines",
  addLine: "Free line",
  addDiscount: "Discount",
  catalogTitle: "Your price list",
  catalogHint: "One click drops the line in, price included.",
  catalogToQuote: "to be priced",
  colDesignation: "Description",
  colQty: "Qty",
  colUnit: "Unit price",
  colTax: "Tax",
  colLineTotal: "Line total",
  discountLine: "Commercial discount",
  removeLine: "Remove this line",
  noLines: "No lines yet. Pick something from your price list, or add a free line.",

  notesTitle: "Notes",
  notesHint: "Anything you want to tell the client — printed on the document.",

  subtotal: "Subtotal",
  discount: "Discount",
  totalHT: "Net total",
  totalTTC: "Total due",

  dates: "Dates",
  issuedOn: "Issued on",
  validUntil: "Valid until",
  dueOn: "Payable by",

  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  unsaved: "Unsaved changes",
  leaveConfirm: "Some changes are not saved. Leave anyway?",
  backToSpace: "Your space",
  print: "Print / PDF",
  convert: "Create invoice",
  converting: "Creating…",
  del: "Delete",
  delConfirm: "Delete this document for good?",
  statusLabel: "Status",
  convertedFrom: "Issued from quote",

  quoteWord: "Quote",
  invoiceWord: "Invoice",
  issuerWord: "From",
  recipientWord: "Bill to",
  numberWord: "No.",
  signature: "Agreed — date and signature",
  page: "Document issued by",

  errorSave: "Could not save.",
  errorLoad: "Data unavailable.",

  tab: {
    editor: "Current quote",
    quotes: "My quotes",
    invoices: "Invoices",
    clients: "Clients",
    catalog: "Price list",
    dashboard: "Dashboard",
    settings: "Settings",
  },

  units: {
    unite: "unit", heure: "hour", jour: "day", forfait: "fixed",
    m2: "m²", ml: "lm", kg: "kg",
  },
  unitsShort: {
    unite: "u", heure: "h", jour: "d", forfait: "fix.",
    m2: "m²", ml: "lm", kg: "kg",
  },
  colUnit2: "Unit",

  auto: {
    idle: "Saved",
    pending: "Unsaved changes…",
    saving: "Saving…",
    savedAt: (time: string) => `Saved at ${time}`,
    failed: "Could not save — your entries are still on screen.",
    retry: "Try again",
  },

  voice: {
    start: "Dictate the quote",
    stop: "Finish dictating",
    listening: "Listening…",
    transcribing: "Transcribing…",
    analysing: "Reading it…",
    hint: "Dictate your work: “fit two radiators at four hundred and twenty euros each, plus a day of labour”.",
    heard: "Heard:",
    applied: (n: number) => `${n} line${n > 1 ? "s" : ""} added.`,
    replaced: (n: number) => `Quote replaced with ${n} line${n > 1 ? "s" : ""}.`,
    nothing: "Nothing priceable in that dictation. Try again, naming the work and its price.",
    denied: "Microphone denied. Allow microphone access in your browser, then try again.",
    unsupported: "This browser cannot record from the microphone.",
    error: "The dictation did not go through.",
    speakToggle: "Spoken confirmation",
    examples: "Things you can say",
    ex1: "“Two hours of labour at sixty euros.”",
    ex2: "“Add a ten percent discount.”",
    ex3: "“Start again, clear everything.”",
  },

  list: {
    search: "Search a number, a client…",
    all: "All",
    open: "Open",
    duplicate: "Duplicate",
    none: "No document matches.",
    totalRow: (n: number, amount: string) => `${n} document${n > 1 ? "s" : ""} · ${amount}`,
  },

  clients: {
    title: "Client list",
    add: "New client",
    search: "Name, company, phone, email",
    company: "Company",
    siret: "Company number",
    notesLabel: "Internal notes",
    fromVoice: "Met on the phone",
    fromPortal: "Entered here",
    save: "Save client",
    del: "Delete record",
    delConfirm: "Delete this record? The journal still keeps what happened.",
    useInQuote: "Put on the quote",
    emptyT: "No clients",
    emptyD: "Add one, or let the receptionist write them in call after call.",
    docsCount: (n: number) => `${n} document${n > 1 ? "s" : ""}`,
    needName: "Give at least a name or a company.",
  },

  cat: {
    title: "Your price list",
    lead: "Seeded from your website the first time. From then on, it is yours.",
    addItem: "New item",
    addCategory: "New section",
    noCategory: "No section",
    itemName: "Item",
    price: "Price",
    purchase: "Cost",
    margin: "Margin",
    toQuote: "To be priced",
    toQuoteHint: "Item with no published price: it is priced case by case.",
    categoryName: "Section name",
    color: "Colour",
    delItem: "Delete item",
    delCategory: "Delete section",
    delCategoryConfirm: "Delete this section? Its items are kept and fall back to “no section”.",
    emptyT: "Empty price list",
    emptyD: "Your website shows no usable price: build your list by hand.",
    count: (n: number) => `${n} item${n > 1 ? "s" : ""}`,
  },

  dash: {
    title: "Your activity",
    lead: "What your quotes produced, over the last twelve months.",
    quoted: "Quotes issued",
    accepted: "Quotes accepted",
    conversion: "Acceptance rate",
    invoiced: "Invoiced",
    paid: "Collected",
    outstanding: "Still owed",
    avgQuote: "Average quote",
    byMonth: "Month by month",
    topItems: "What sells",
    topEmpty: "Nothing sold yet.",
    noData: "No documents yet: the figures will appear here.",
    monthQuotes: "Quotes",
    monthInvoices: "Invoices",
  },

  set: {
    title: "Document settings",
    lead: "What your website does not say, and an accounting document requires. A field left empty falls back to your website.",
    identity: "Identity",
    payment: "Payment",
    legal: "Notices",
    inherited: (value: string) => `Website: ${value}`,
    companyName: "Legal name",
    legalForm: "Legal form",
    siret: "Company number",
    vatNumber: "VAT number",
    address: "Address",
    postalCode: "Postcode",
    city: "City",
    country: "Country",
    phone: "Phone",
    email: "Email",
    website: "Website",
    logoUrl: "Logo (URL)",
    iban: "IBAN",
    bic: "BIC",
    paymentMethod: "Payment methods accepted",
    paymentDays: "Payment terms (days)",
    validityDays: "Quote validity (days)",
    taxRateDefault: "Default tax rate (%)",
    footerNotes: "Extra notices at the foot of the document",
    footerHint: "They are added to the legal notices, they do not replace them.",
    insuranceLabel: "Insurance",
    insuranceDetail: "Insurance details",
    save: "Save settings",
    saved: "Settings saved",
  },
};

export function docStrings(lang: Lang): DocStrings {
  return lang === "en" ? EN : FR;
}
